# Generated by Django 5.2.1 on 2025-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
