# Generated by Django 5.2.1 on 2025-05-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_codesubmission_ai_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
