# Generated by Django 5.2.1 on 2025-05-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_codesubmission_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='verdict',
        ),
    ]
